index:
    path: /
    controller: App\Controller\ShortnerController::index

url_store:
    path: /store/url
    controller: App\Controller\ShortnerController::store

shorty_redirect:
    path: /{shorty_url}
    controller: App\Controller\ShortnerController::redirectToStoredUrl
